// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtHoEVehLUg7fWhNbQtRRPT4C-9ugCH9c',
    appId: '1:66674081684:web:43ed608b5c75f1bd181981',
    messagingSenderId: '66674081684',
    projectId: 'd-car-racing-game-9eba2',
    authDomain: 'd-car-racing-game-9eba2.firebaseapp.com',
    storageBucket: 'd-car-racing-game-9eba2.appspot.com',
    measurementId: 'G-395NYDXNZQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEHb3oJ67HIBn_Z_6oRVmUPUGV_FpC0aw',
    appId: '1:66674081684:android:410e803cbff717f9181981',
    messagingSenderId: '66674081684',
    projectId: 'd-car-racing-game-9eba2',
    storageBucket: 'd-car-racing-game-9eba2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-afGyLAdz5o8ueeRN4NC3ClLSjKhLF6A',
    appId: '1:66674081684:ios:a2d1ab43640f9430181981',
    messagingSenderId: '66674081684',
    projectId: 'd-car-racing-game-9eba2',
    storageBucket: 'd-car-racing-game-9eba2.appspot.com',
    iosClientId: '66674081684-2ing71klbpl22oiqdsnbet6dt1ron30i.apps.googleusercontent.com',
    iosBundleId: 'com.example.mutliUser2dCarRacingGameWithGroupChatUsingFlutterAndFirebase7june',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-afGyLAdz5o8ueeRN4NC3ClLSjKhLF6A',
    appId: '1:66674081684:ios:7e7ea2db9b6f72c3181981',
    messagingSenderId: '66674081684',
    projectId: 'd-car-racing-game-9eba2',
    storageBucket: 'd-car-racing-game-9eba2.appspot.com',
    iosClientId: '66674081684-3tnk51r1qjqt324hr34h685cf3a9lv2j.apps.googleusercontent.com',
    iosBundleId: 'com.example.mutliUser2dCarRacingGameWithGroupChatUsingFlutterAndFirebase7june.RunnerTests',
  );
}
